apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: nginx-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app
    repoURL: https://github.com/smartlizzard/nginx-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
